#!/bin/bash

set -e

if ! command -v gum &> /dev/null; then
    echo "[!] Gum is not installed, please install the tool"
    echo " > https://github.com/charmbracelet/gum"
    exit 1
fi

TYPE=$(gum choose "fix" "feat" "docs" "style" "refactor" "test" "chore" "revert")
SCOPE=$(gum input --placeholder "scope")

test -n "$SCOPE" && SCOPE="($SCOPE)"

SUMMARY=$(gum input --value "$TYPE$SCOPE: " --placeholder "Summary of this change")
DESCRIPTION=$(gum write --placeholder "Details of this change (CTRL+D to finish)")

if [ -z "$(git status -s -uno | grep -v '^ ' | awk '{print $2}')" ]; then 
    gum confirm "No staged files. Commit all?" && git add .
fi

gum confirm "Commit changes?" && git commit -m "$SUMMARY" -m "$DESCRIPTION"


