#!/bin/bash

set -e

export CODEQL_SUMMARIZE=${CODEQL_SUMMARIZE:=$HOME/.codeql/summarize}

if [[ ! -d $CODEQL_SUMMARIZE ]]; then
    echo "[!] CodeQL Summarize isn't installed... Cloning now"
    mkdir -p $CODEQL_SUMMARIZE
    git clone \
        https://github.com/advanced-security/codeql-summarize \
        $CODEQL_SUMMARIZE
fi

# if any arguments are passed, pass them to codeql-summarize
if [[ $# -gt 0 ]]; then
    $CODEQL_SUMMARIZE/codeql-summarize $@
else 
    REPO=$(gum input --placeholder "Repository (owner/repo)")
    echo "Repository :: ${REPO}"

    LANG=$(gum choose "cpp" "csharp" "java" "javascript" "go" "python" "ruby")

    $CODEQL_SUMMARIZE/codeql-summarize -l $LANG -r $REPO
fi
