#!/bin/bash 
# Select the CodeQL Binary to use 

# Mason / Neovim
if [ -f "$HOME/.local/share/nvim/mason/bin/codeql" ]; then
    $HOME/.local/share/nvim/mason/bin/codeql $@

else
    # Default (gh cli)
    SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

    if ! command -v gh codeql &> /dev/null; then 
        $SCRIPT_DIR/codeql-update
    fi 

    gh codeql $@

fi


