#!/bin/bash

set -e

if ! command -v gum &> /dev/null; then
    echo "[!] Gum is not installed, please install the tool"
    echo " > https://github.com/charmbracelet/gum"
    exit 1
fi

CODEQL_DATABASES="${CODEQL_DATABASES:=$PWD/.codeql-databases}"

SOURCE="github.com"

REPO=$(gum input --placeholder "Repository (owner/repo)")

OWNER=$(echo $REPO | cut -d'/' -f1)
NAME=$(echo $REPO | cut -d'/' -f2)

echo "Name :: ${NAME[1]}"

LANG=$(gum choose "cpp" "csharp" "java" "javascript" "go" "python" "ruby")

OUTPUT_DIR="$CODEQL_DATABASES/$SOURCE/$OWNER/$NAME"
OUTPUT="$OUTPUT_DIR/$LANG.zip"


echo "[+] $REPO ($lang)"
echo "[+] Saving to :: $OUTPUT"

mkdir -p "$OUTPUT_DIR"

# https://docs.github.com/en/enterprise-cloud@latest/rest/code-scanning?apiVersion=2022-11-28#get-a-codeql-database-for-a-repository
curl \
  -H "Accept: application/zip" \
  -H "Authorization: token $GITHUB_TOKEN" \
  -L -o "$OUTPUT" \
  https://api.github.com/repos/$REPO/code-scanning/codeql/databases/$LANG

# Unzip it...
unzip "$OUTPUT" -d $OUTPUT_DIR

