#!/bin/bash

# Update command
update() {
    sudo apt-get update -y
    sudo apt-get upgrade -y
    sudo apt-get dist-upgrade -y
    sudo apt-get autoremove
}

# Color support
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


# ls commands
alias ll="ls -l"
alias la="ls -la"

whatismyip() {
    MYIP="$(dig +short myip.opendns.com @resolver1.opendns.com)"
    echo ${MYIP}

    if [ "$MYIP" == "$SERVER_EXT_IP" ]; then
        echo "Using external server (vpn)"
    fi 
}

# Watch commands
alias watch-ip="watch --color ifconfig"
alias watch-net="watch --color netstat -lpn -u -t"
alias watch-dir="watch --color ls --color -las"

