#!/bin/bash
# Work commands

alias work-mount="sudo mount"

# Vbox VM's
alias work-vm-kali="vboxheadless -s Kali &"
alias work-vm-kali-poweroff="VBoxManage controlvm 'Kali' savestate"

alias work-vm-test="vboxheadless -s 'Ubuntu-TestServer' &"
alias work-vm-test-poweroff="VBoxManage controlvm 'Ubuntu-TestServer' savestate"

# java
java-jar() {
    # TODO check DPI (for 4K)
    DPI=""
    java $DPI -jar $@
}


# > Work: Security Testing
## Web testing

work-web-burp() {
    java-jar burpsuite
}
work-web-chrome(){
    google-chrome --args --disable-web-security
}

work-web(){
    work-mount
    work-web-burp &
    work-web-chome &
}


