#!/bin/bash

# Development
alias python="python3"
alias freeze="pip freeze > requirements.txt"
alias pyinstall="python ./setup.py install"


# JavaScript

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

