#!/bin/bash

# vpn commands
alias vpn="sudo /usr/sbin/openvpn && ip.dns"

# server commands
alias server.tmux="ssh $@ -t 'tmux a -t console || tmux new -s console'"

server.mount(){
    if [ ! -d $1 ]; then; mkdir -p $1; fi
    # TODO: Mount server dir
    sshfs -p $SERVER_EXT_PORT -o allow_other $SERVER_EXT_USER@$SERVER_EXT_IP:$SERVER_EXT_RDIR $SERVER_EXT_DIR
}

server.unmount() {
    umount $@
}

# Virtiual machines
if [ -x /usr/bin/vboxmanage ]; then
    alias vm="vboxmanage --startvm $@"
    alias vm.headless="vboxheadless --startvm $@"
    alias vm.create="vboxmanage createvm --register --name $@"
    alias vm.rm="vboxmanage unregistervm $@"
    alias vm.list="vboxmanage list vms"
fi
# TODO: Add VMWare support
