#!/bin/bash

# Basic server aliases
server() {
    echo ""
    echo "External < $SERVER_EXT_IP:$SERVER_EXT_PORT >"
    echo "Internal < $SERVER_INT_IP:$SERVER_INT_PORT >"
    echo ""
}

server-ssh(){
	ssh -p $SERVER_EXT_PORT $SERVER_EXT_USER@$SERVER_EXT_IP -t 'tmux a -t console || tmux new -s console'
}

server-mount() {
    if [ ! -d $SERVER_EXT_DIR ]; then
        mkdir $SERVER_EXT_DIR
    fi
    # Mount server dir
    sshfs -p $SERVER_EXT_PORT -o allow_other $SERVER_EXT_USER@$SERVER_EXT_IP:$SERVER_EXT_RDIR $SERVER_EXT_DIR
}
server-unmount() {
    umount $SERVER_EXT_DIR
}

server-vpn() {
    sudo /usr/sbin/openvpn $SERVER_EXT_OPENVPN
}

