#!/bin/bash

# Update command
update() {
    sudo apt-get update -y
    sudo apt-get upgrade -y
    sudo apt-get dist-upgrade -y
    sudo apt-get autoremove
}

# Color support
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


# ls commands
alias ll="ls -l"
alias la="ls -la"

# Server aliases
server() {
    echo ""
    echo "External < $SERVER_EXT_IP:$SERVER_EXT_PORT >"
    echo "Internal < $SERVER_INT_IP:$SERVER_INT_PORT >"
    echo ""
}

server-ssh(){
	ssh -p $SERVER_EXT_PORT $SERVER_EXT_USER@$SERVER_EXT_IP -t 'tmux a -t console || tmux new -s console'
}

server-mount() {
    if [ ! -d $SERVER_EXT_DIR ]; then
        mkdir $SERVER_EXT_DIR
    fi
    # Mount server dir
    sshfs -p $SERVER_EXT_PORT -o allow_other $SERVER_EXT_USER@$SERVER_EXT_IP:$SERVER_EXT_RDIR $SERVER_EXT_DIR
}
server-unmount() {
    umount $SERVER_EXT_DIR
}

server-vpn() {
    sudo /usr/sbin/openvpn $SERVER_EXT_OPENVPN
}

# Watch commands
alias watch-ip="watch --color ifconfig"
alias watch-net="watch --color netstat -lpn -u -t"
alias watch-net-ext="watch --color netstat -lpn -u -t | grep '0.0.0.0'"
alias watch-dir="watch --color ls --color -las"

