#!/bin/bash
# Work commands

alias work-mount="sudo mount"

# Vbox VM's
alias work-vm-kali="vboxheadless -s Kali &"
alias work-vm-kali-poweroff="VBoxManage controlvm 'Kali' savestate"

alias work-vm-test="vboxheadless -s 'Ubuntu-TestServer' &"
alias work-vm-test-poweroff="VBoxManage controlvm 'Ubuntu-TestServer' savestate"


#====== Web testing ======#

work-web-burp() {

}
work-web-chrome(){
    google-chrome
}

work-web(){
    work-mount
    work-web-burp &
    work-web-chome &
}


