#!/bin/bash

set -e

if ! command -v gum &> /dev/null; then
    echo "[!] Gum is not installed, please install the tool"
    echo " > https://github.com/charmbracelet/gum"
    exit 1
fi

CODEQL_DATABASES="${CODEQL_DATABASES:=$PWD/.codeql-databases}"

REPO=$(gum input --placeholder "Repository (owner/repo)")
NAME=(${REPO//\//_})
echo "Name :: ${NAME[1]}"
LANG=$(gum choose "cpp" "csharp" "java" "javascript" "go" "python" "ruby")
OUTPUT="$CODEQL_DATABASES/$NAME-$LANG"

echo "[+] $REPO ($lang)"
echo "[+] Saving to :: $OUTPUT.zip"

# https://docs.github.com/en/enterprise-cloud@latest/rest/code-scanning?apiVersion=2022-11-28#get-a-codeql-database-for-a-repository
curl \
  -H "Accept: application/zip" \
  -H "Authorization: token $GITHUB_TOKEN" \
  -L -o "$OUTPUT.zip" \
  https://api.github.com/repos/$REPO/code-scanning/codeql/databases/$LANG

# Unzip it...
unzip "$OUTPUT.zip" -d $OUTPUT

