# Sources
# - https://github.com/ThePrimeagen/.dotfiles/blob/master/tmux/.tmux.conf
# - https://yesmeck.github.io/tmuxrc/

# Colours
# - https://jdhao.github.io/2018/10/19/tmux_nvim_true_color/

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"

set-environment -g PATH "/opt/homebrew/bin:$PATH"

set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# All things pane / windows related
bind J split-window -h
bind K split-window -v
# Vimlike bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# misc
set -g base-index 1

# Vimlike copy mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# >>>>> Script / Actions <<<<<
bind-key -r R run-shell "tmux source-file ~/.tmux.conf; tmux display 'Reloaded config'"
# Dev
bind-key -r D run-shell "tmux split-window -v -l 20 'dev'"
# Running/Testing Code
bind-key -r F5 run-shell "tmux split-window -v -l 20 'dev run -q main; read'"
bind-key -r F10 run-shell "tmux split-window -v -l 20 'dev run -q test; read'"

# Commiting code
bind-key -r C run-shell "tmux split-window -v -l 20 'commit'"


# Plugins - https://github.com/tmux-plugins/tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Theme - https://github.com/janoamaral/tokyo-night-tmux
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_theme night
# set -g @tokyo-night-tmux_transparent 1

set -g @tokyo-night-tmux_show_git 1             # local git status
set -g @tokyo-night-tmux_show_wbg 1             # GitHub / GitLab stats
# set -g @tokyo-night-tmux_show_netspeed 1        # network speed
# set -g @tokyo-night-tmux_show_battery_widget 1  # battery level
# set -g @tokyo-night-tmux_show_music 1           # now playing
set -g @tokyo-night-tmux_show_path 1            # current path
set -g @tokyo-night-tmux_show_hostname 1        # machine hostname

run '~/.tmux/plugins/tpm/tpm'

